#!/bin/sh 

NAME="hmp2"                                                   # Name of the application
PROJECT_DIR="$( cd "$( dirname "$0" )/../../" && pwd )"       # Base project directory
DJANGODIR="$( cd "$( dirname "$0" )/../" && pwd )"            # Django project directory
SOCKFILE=${PROJECT_DIR}/var/run/gunicorn.sock                 # we will communicte using this unix socket
USER=ibdmdb                                                   # the user to run as
GROUP=broad                                                   # the group to run as
NUM_WORKERS=2                                                 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=hmp2.settings                          # which settings file should Django use
DJANGO_WSGI_MODULE=hmp2.wsgi                                  # WSGI module name

echo "Starting $NAME as `whoami`"

# We have to source another file that has the path to all our binaries
cd $DJANGODIR

# Activate the virtual environment
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=${PROJECT_DIR}/var/log/ibdmdb-cms.gunicorn.log \
  --daemon